export const Permissions = {
  NGO_APPROVE: "NGO_APPROVE",
  NGO_REMOVE: "NGO_REMOVE",

  TASK_CREATE: "TASK_CREATE",
  TASK_VERIFY: "TASK_VERIFY",
  TASK_DELETE: "TASK_DELETE",

  REWARD_CREATE: "REWARD_CREATE",
  REWARD_EDIT: "REWARD_EDIT",
  REWARD_DELETE: "REWARD_DELETE",

  MEMBER_INVITE: "MEMBER_INVITE",
  MEMBER_REMOVE: "MEMBER_REMOVE",

  COMMUNITY_MODERATE: "COMMUNITY_MODERATE",

  AREA_CREATE: "AREA_CREATE",
} as const;

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(Permissions),
};